#!/bin/bash
# TEST.sh — v1.1.0 sample frozen-data generator (+ optional policy run)
# Compatible with Splunk_Frozen_Retention_Policy.sh v1.1.0:
#   age-based retention, skip unconfigured indexes, in-process empty-dir cleanup
#   (Delete_Empty_Folder.sh is not used).
#
# Usage:
#   bash ./TEST.sh              # build mock data + config only
#   bash ./TEST.sh --run        # build, then run the v1.1.0 policy once
#   RUN_POLICY=1 bash ./TEST.sh # same as --run
#
# Optional env overrides (do not reuse policy CONFIG_FILE from a prior shell):
#   TEST_DIR WORK_DIR TEST_CONFIG_FILE TEST_LOG_FILE TEST_LOCK_FILE POLICY

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
POLICY="${POLICY:-$SCRIPT_DIR/Splunk_Frozen_Retention_Policy.sh}"

TEST_DIR="${TEST_DIR:-/tmp/frozen_test}"
WORK_DIR="${WORK_DIR:-/tmp/frozen_test_work}"
TEST_CONFIG_FILE="${TEST_CONFIG_FILE:-$WORK_DIR/index_size.conf}"
TEST_LOG_FILE="${TEST_LOG_FILE:-$WORK_DIR/Splunk_Frozen_Data.log}"
TEST_LOCK_FILE="${TEST_LOCK_FILE:-$WORK_DIR/Splunk_Frozen_Retention_Policy.lock}"

RUN_POLICY="${RUN_POLICY:-0}"
for arg in "$@"; do
    case "$arg" in
        --run|-r) RUN_POLICY=1 ;;
        --help|-h)
            sed -n '2,14p' "$0"
            exit 0
            ;;
    esac
done

mkdir -p "$WORK_DIR" "$(dirname "$TEST_CONFIG_FILE")" "$(dirname "$TEST_LOG_FILE")" "$(dirname "$TEST_LOCK_FILE")"
rm -rf "$TEST_DIR"
mkdir -p "$TEST_DIR"

echo "=== TEST.sh (v1.1.0) building mock frozen data ==="
echo "FROZEN_PATH (TEST_DIR)=$TEST_DIR"
echo "TEST_CONFIG_FILE=$TEST_CONFIG_FILE"

# size_mb retention_days
declare -A TEST_INDEXES
TEST_INDEXES["index1"]="100 7"
TEST_INDEXES["index2"]="200 3"
TEST_INDEXES["index3"]="150 5"
TEST_INDEXES["index4"]="50 2"
TEST_INDEXES["index5"]="300 10"
TEST_INDEXES["index6"]="250 15"
TEST_INDEXES["index7"]="180 20"
TEST_INDEXES["index8"]="120 8"
TEST_INDEXES["test"]="100 7"
# Age probe: all files old, short span (v1.0.0 span logic would wrongly skip)
TEST_INDEXES["retention_age"]="5000 30"
# Size probe: young files over size limit
TEST_INDEXES["size_probe"]="5 365"
TEST_INDEXES["empty_idx"]="100 30"

{
    echo "# Generated by TEST.sh for Splunk Frozen Retention Policy v1.1.0"
    echo "# index=name,size=MB,retention=days (oldest file age vs now)"
    echo
    for INDEX in $(printf '%s\n' "${!TEST_INDEXES[@]}" | sort); do
        SIZE=$(awk '{print $1}' <<<"${TEST_INDEXES[$INDEX]}")
        RETENTION=$(awk '{print $2}' <<<"${TEST_INDEXES[$INDEX]}")
        echo "index=$INDEX,size=$SIZE,retention=$RETENTION"
    done
    echo
    echo "# Intentionally omitted: unconfigured (must be skipped_unconfigured)"
} >"$TEST_CONFIG_FILE"

make_file() {
    local path="$1" mb="$2" days_ago="$3"
    mkdir -p "$(dirname "$path")"
    dd if=/dev/zero of="$path" bs=1M count="$mb" status=none 2>/dev/null
    touch -d "$days_ago days ago" "$path"
}

for INDEX in "${!TEST_INDEXES[@]}"; do
    case "$INDEX" in
        retention_age|size_probe|empty_idx) continue ;;
    esac

    INDEX_DIR="$TEST_DIR/$INDEX"
    mkdir -p "$INDEX_DIR"

    for i in {1..10}; do
        make_file "$INDEX_DIR/log_$i.log" "$((i * 5))" "$((i + 1))"
    done

    if [[ "$INDEX" == "index6" || "$INDEX" == "index7" || "$INDEX" == "test" ]]; then
        for j in {1..5}; do
            make_file "$INDEX_DIR/sub_dir/sub_log_$j.log" "$((j * 3))" "$((j + 2))"
        done
    fi
done

# Nested large file under test/
make_file "$TEST_DIR/test/test1/large_file.log" 200 5
find "$TEST_DIR/test" -exec touch -d "5 days ago" {} +

# retention_age: ~100d old, span ~3d
make_file "$TEST_DIR/retention_age/old_a.log" 2 100
make_file "$TEST_DIR/retention_age/old_b.log" 2 97

# size_probe: 4+4 MB > 5 MB limit; ages within retention=365
make_file "$TEST_DIR/size_probe/older.log" 4 10
make_file "$TEST_DIR/size_probe/newer.log" 4 1

# empty configured index
mkdir -p "$TEST_DIR/empty_idx"

# not in conf — must remain untouched
make_file "$TEST_DIR/unconfigured/keep_me.log" 4 200

echo
echo "Mock tree summary (MB):"
du -cms "$TEST_DIR"/* 2>/dev/null | sort -n | tail -n 25 || true
echo
echo "Config: $TEST_CONFIG_FILE ($(grep -c '^index=' "$TEST_CONFIG_FILE") indexes)"
echo "Unconfigured dir: $TEST_DIR/unconfigured"

if [[ "$RUN_POLICY" == "1" ]]; then
    if [[ ! -f "$POLICY" ]]; then
        echo "ERROR: policy script not found: $POLICY" >&2
        exit 1
    fi
    : >"$TEST_LOG_FILE"
    echo
    echo "=== Running Splunk_Frozen_Retention_Policy.sh (v1.1.0) ==="
    # Export policy vars explicitly (do not rely on ambient shell CONFIG_FILE)
    export FROZEN_PATH="$TEST_DIR"
    export CONFIG_FILE="$TEST_CONFIG_FILE"
    export LOG_FILE="$TEST_LOG_FILE"
    export LOCK_FILE="$TEST_LOCK_FILE"
    bash "$POLICY"
    echo
    echo "=== Last log lines ==="
    tail -n 40 "$TEST_LOG_FILE" || true
    echo
    echo "Full log: $TEST_LOG_FILE"
else
    echo
    echo "Data only. Run the v1.1.0 policy with:"
    echo "  bash $0 --run"
    echo "Or:"
    echo "  FROZEN_PATH=$TEST_DIR CONFIG_FILE=$TEST_CONFIG_FILE LOG_FILE=$TEST_LOG_FILE LOCK_FILE=$TEST_LOCK_FILE \\"
    echo "    bash $POLICY"
fi
